---

- name: Set Parent Variable
  shell: echo "parent_variable"
  register: default_gateway_ip

- name: Print Parent Variable
  debug:
    msg: "{{ default_gateway_ip.stdout }}"

- name: import_child_var.yml
  import_tasks: import_child_var.yml
  when: false

- name: Print Parent Variable
  debug:
    msg: "{{ default_gateway_ip.stdout }}"
